spring.application.name=catalogo3d

spring.data.mongodb.uri=mongodb://localhost:27017/catalogo3d
spring.data.mongodb.database=catalogo3d

server.port=8080

spring.jackson.serialization.write-dates-as-timestamps=false
