spring.application.name=catalogo3d

spring.data.mongodb.uri=mongodb+srv://thebash1:8IxXnxUoofpqd8er@cluster0.1tvpnj2.mongodb.net/?appName=cluster0
spring.data.mongodb.database=catalogo3d

server.port=8080

spring.jackson.serialization.write-dates-as-timestamps=false
